version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: creditpro-api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=creditpro;Username=postgres;Password=postgres
      DynamoDb__TableName: creditpro-audit-events
      DynamoDb__Region: us-east-1
      DynamoDb__ServiceUrl: http://dynamodb:8000
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      postgres:
        condition: service_healthy
      dynamodb:
        condition: service_started
      dynamodb-init:
        condition: service_completed_successfully

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: creditpro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  dynamodb:
    image: amazon/dynamodb-local:latest
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    ports:
      - "8001:8000"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data

  dynamodb-init:
    image: amazon/aws-cli:2.18.14
    depends_on:
      dynamodb:
        condition: service_started
    entrypoint: >
      sh -c "
      until aws dynamodb list-tables --endpoint-url http://dynamodb:8000 >/dev/null 2>&1; do
        echo 'Esperando a DynamoDB...';
        sleep 2;
      done;
      aws dynamodb describe-table --table-name creditpro-audit-events --endpoint-url http://dynamodb:8000 ||
      aws dynamodb create-table
        --table-name creditpro-audit-events
        --attribute-definitions AttributeName=applicationId,AttributeType=S AttributeName=timestamp,AttributeType=S
        --key-schema AttributeName=applicationId,KeyType=HASH AttributeName=timestamp,KeyType=RANGE
        --billing-mode PAY_PER_REQUEST
        --endpoint-url http://dynamodb:8000 &&
      aws dynamodb update-time-to-live --table-name creditpro-audit-events --time-to-live-specification Enabled=false --endpoint-url http://dynamodb:8000
      "
    environment:
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
      AWS_DEFAULT_REGION: us-east-1
    restart: "no"

volumes:
  pg-data:
  dynamodb-data:
